import { useEffect, useMemo, useState } from 'react';
import { ErrorState, KeyValue, Loading } from '../components/common';
import { ReviewActions, type ReviewTarget } from '../components/ReviewActions';
import { SYN_SCORE_KINDS, type SynScoreKind } from '../lib/contracts';
import { downloadJson } from '../lib/download';
import { fmtInt, fmtNum, reasonLabel, tierLabel } from '../lib/format';
import { exportLedger } from '../lib/ledger';
import { makePolicy, PolicyError, type Policy } from '../lib/policy';
import { checkExpectations, decideSandbox, joinDemo } from '../lib/sandbox';
import { scenarioId } from '../lib/scenario';
import { useCore, useStore } from '../store';

export function SandboxView() {
  const core = useCore();
  const { sandbox, ensureSandbox, events, record, undo } = useStore();
  const [preset, setPreset] = useState<string>('');
  const [acceptText, setAcceptText] = useState('');
  const [reviewText, setReviewText] = useState('');
  const [gapText, setGapText] = useState('');
  const data = sandbox.status === 'ready' ? sandbox.data : null;

  useEffect(() => {
    ensureSandbox();
  }, [ensureSandbox]);
  useEffect(() => {
    if (data) {
      const prev = document.title;
      document.title = `SYNTHETIC · ${data.badge} · Sandbox · Entity Resolution Decision Lab`;
      return () => {
        document.title = prev;
      };
    }
    return undefined;
  }, [data]);
  useEffect(() => {
    if (data && !preset && data.policies[0]) {
      const p = data.policies[0];
      setPreset(p.preset);
      setAcceptText(String(p.policy.accept_min));
      setReviewText(String(p.policy.review_min));
      setGapText(String(p.policy.ambiguity_gap));
    }
  }, [data, preset]);

  const policy = useMemo<{ policy: Policy | null; message: string | null }>(() => {
    const n = [acceptText, reviewText, gapText].map((t) => (t.trim() === '' ? NaN : Number(t)));
    if (n.some((x) => !Number.isFinite(x))) return { policy: null, message: 'every threshold must be a finite number' };
    try {
      return { policy: makePolicy(n[0], n[1], n[2]), message: null };
    } catch (e) {
      return { policy: null, message: e instanceof PolicyError ? e.message : String(e) };
    }
  }, [acceptText, reviewText, gapText]);

  if (!core) return null;
  if (sandbox.status === 'loading' || sandbox.status === 'idle') return <Loading what="the synthetic sandbox fixture" />;
  if (sandbox.status === 'error') return <ErrorState error={sandbox.error} title="Sandbox fixture unavailable" />;
  if (!data) return null;
  const presetDef = data.policies.find((p) => p.preset === preset);
  const edited = presetDef && policy.policy ? policy.policy.accept_min !== presetDef.policy.accept_min || policy.policy.review_min !== presetDef.policy.review_min || policy.policy.ambiguity_gap !== presetDef.policy.ambiguity_gap : false;
  const sid = scenarioId({ kind: 'synthetic', preset: preset || 'default' });
  const join = joinDemo(data);
  const byId = (id: string) => data.records.a.find((r) => r.id === id) ?? null;
  const bById = (id: string) => data.records.b.find((r) => r.id === id) ?? null;
  const synEvents = events.filter((e) => e.scenario_id.startsWith('synthetic:'));

  return (
    <>
      <div className="synthetic-banner" role="note" data-testid="synthetic-badge">
        {data.badge}
      </div>
      <h2 style={{ marginTop: 0 }}>Synthetic mechanics sandbox</h2>
      <p className="note">
        Invented A/B records and fixture scores that demonstrate the policy mechanics. Generated by <code>{data.generated_by}</code>. Nothing here enters a real-snapshot figure; scenario ids are prefixed{' '}
        <code>synthetic:</code>, and receipts are refused for this view.
      </p>
      <div className="synthetic-box">
        <h3 style={{ marginTop: 0 }}>Score kinds (fixtures, never a learned model)</h3>
        <KeyValue rows={SYN_SCORE_KINDS.map((k) => [k, data.score_kinds[k]])} />
      </div>

      <div className="panel">
        <h3 style={{ marginTop: 0 }}>Policy</h3>
        <div className="controls">
          <label>
            preset
            <select
              value={preset}
              data-testid="sandbox-preset"
              onChange={(e) => {
                const p = data.policies.find((x) => x.preset === e.target.value);
                if (!p) return;
                setPreset(p.preset);
                setAcceptText(String(p.policy.accept_min));
                setReviewText(String(p.policy.review_min));
                setGapText(String(p.policy.ambiguity_gap));
              }}
            >
              {data.policies.map((p) => (
                <option key={p.preset} value={p.preset}>
                  {p.preset}: accept {fmtNum(p.policy.accept_min)}, review {fmtNum(p.policy.review_min)}, gap {fmtNum(p.policy.ambiguity_gap)}
                </option>
              ))}
            </select>
          </label>
          <label>
            accept_min
            <input type="number" min="0" max="1" step="any" value={acceptText} onChange={(e) => setAcceptText(e.target.value)} data-testid="sandbox-accept" />
          </label>
          <label>
            review_min
            <input type="number" min="0" max="1" step="any" value={reviewText} onChange={(e) => setReviewText(e.target.value)} data-testid="sandbox-review" />
          </label>
          <label>
            ambiguity_gap
            <input type="number" min="0" max="1" step="any" value={gapText} onChange={(e) => setGapText(e.target.value)} data-testid="sandbox-gap" />
          </label>
        </div>
        {policy.message ? (
          <p className="bad-text small" role="alert">
            {policy.message}
          </p>
        ) : edited ? (
          <p className="small muted">Edited policy (differs from preset {preset}); expected-value checks compare against the preset's expectations and may fail by design.</p>
        ) : null}
        <p className="small">
          SYNTHETIC scenario id: <code data-testid="sandbox-scenario-id">{sid}</code>
        </p>
      </div>

      <h3>Cases</h3>
      {data.cases.map((c) => {
        const a = byId(c.a_id);
        const checks = policy.policy ? checkExpectations(data, c.case_id, preset, policy.policy) : [];
        const decisions = policy.policy ? SYN_SCORE_KINDS.map((k) => decideSandbox(data, c.a_id, k, policy.policy as Policy)) : [];
        const candidateIds = [...new Set(data.candidates.filter((x) => x.a_id === c.a_id).map((x) => x.b_id))];
        const target: ReviewTarget = {
          scenario_id: sid,
          a_id: c.a_id,
          method_version: 'synthetic_rules_like',
          evidence_ref: { case_id: c.case_id, source: 'synthetic_sandbox' },
          candidates: [...candidateIds.map((b) => ({ b_id: b, origin: 'candidate' })), ...(data.labels[c.a_id] ?? []).filter((b) => !candidateIds.includes(b)).map((b) => ({ b_id: b, origin: 'truth' }))],
        };
        return (
          <section key={c.case_id} className="synthetic-box" aria-labelledby={`h-${c.case_id}`} data-testid={`sandbox-case-${c.case_id}`}>
            <h4 id={`h-${c.case_id}`} style={{ marginTop: 0 }}>
              <code>{c.case_id}</code> <span className="badge warn">SYNTHETIC</span>
            </h4>
            <p className="small">{c.purpose}</p>
            <div className="record-pair">
              <div className="record-card">
                <strong>A {c.a_id}</strong>
                {a ? <KeyValue rows={[['title', a.title], ['artist credit', a.artist_credit], ['year', a.year === null ? 'null' : String(a.year)]]} /> : <p className="muted">record not in fixture</p>}
              </div>
              {candidateIds.map((b) => {
                const rb = bById(b);
                const truth = (data.labels[c.a_id] ?? []).includes(b);
                return (
                  <div className="record-card" key={b}>
                    <strong>B {b}</strong> {truth ? <span className="badge ok">truth</span> : null}
                    {rb ? <KeyValue rows={[['title', rb.title], ['artist credit', rb.artist_credit], ['year', rb.year === null ? 'null' : String(rb.year)]]} /> : <p className="muted">record not in fixture</p>}
                  </div>
                );
              })}
              {candidateIds.length === 0 ? <div className="record-card muted">no candidate for this A record</div> : null}
            </div>
            <table>
              <thead>
                <tr>
                  <th className="left">candidate B</th>
                  {SYN_SCORE_KINDS.map((k) => (
                    <th key={k}>{k}</th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {data.candidates
                  .filter((x) => x.a_id === c.a_id)
                  .map((x) => (
                    <tr key={x.b_id}>
                      <td className="mono">{x.b_id}</td>
                      {SYN_SCORE_KINDS.map((k) => (
                        <td key={k}>{fmtNum(x.values[k])}</td>
                      ))}
                    </tr>
                  ))}
              </tbody>
            </table>
            <table>
              <thead>
                <tr>
                  <th className="left">score kind</th>
                  <th className="left">chosen</th>
                  <th>v1</th>
                  <th>v2</th>
                  <th>gap</th>
                  <th className="left">tier</th>
                  <th className="left">reason</th>
                  <th className="left">ambiguous / demoted</th>
                </tr>
              </thead>
              <tbody>
                {decisions.map((d) => (
                  <tr key={d.kind} data-testid={`sandbox-decision-${c.case_id}-${d.kind}`}>
                    <td>{d.kind}</td>
                    <td className="left mono">{d.chosen ?? '—'}</td>
                    <td>{d.row.v1 === null ? 'null' : fmtNum(d.row.v1)}</td>
                    <td>{d.row.v2 === null ? 'null' : fmtNum(d.row.v2)}</td>
                    <td>{d.decision.gap === null ? 'null' : fmtNum(d.decision.gap)}</td>
                    <td className="left">{tierLabel(d.decision.tier)}</td>
                    <td className="left small">{reasonLabel(d.decision.reason)}</td>
                    <td className="left small">
                      {d.decision.ambiguous ? 'ambiguous' : 'not ambiguous'} / {d.decision.demoted ? 'demoted' : 'not demoted'}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
            {checks.length ? (
              <ul className="small" data-testid={`sandbox-checks-${c.case_id}`}>
                {checks.map((k) => (
                  <li key={`${k.key}-${k.field}`}>
                    <span className={k.ok ? 'ok-text' : 'bad-text'}>{k.ok ? '✓ pass' : '✗ fail'}</span> {k.key}.{k.field}: expected {JSON.stringify(k.expected)}, got {JSON.stringify(k.actual)}
                  </li>
                ))}
              </ul>
            ) : (
              <p className="small muted">No expectations recorded for preset {preset || '(none)'}.</p>
            )}
            <SyntheticActions target={target} />
          </section>
        );
      })}

      <h3>Downstream join demonstration</h3>
      <div className="synthetic-box" data-testid="join-demo">
        <p className="small">{data.downstream_fixture.note}</p>
        <KeyValue
          rows={[
            ['fact rows', fmtInt(join.fact_rows)],
            ['conserved row count', fmtInt(join.conserved_row_count)],
            ['rows after joining through the mapping', <span className={join.inflated ? 'bad-text' : 'ok-text'}>{fmtInt(join.joined_rows)}{join.inflated ? ' (inflated)' : ' (conserved)'}</span>],
            ['B ids mapped more than once', join.duplicated_b_ids.length ? join.duplicated_b_ids.join(', ') : 'none'],
            ['units before / after', `${fmtInt(join.units_before)} / ${fmtInt(join.units_after)}`],
          ]}
        />
        <table>
          <thead>
            <tr>
              <th className="left">b_id</th>
              <th className="left">a_id</th>
              <th>units</th>
            </tr>
          </thead>
          <tbody>
            {join.joined.map((r, i) => (
              <tr key={`${r.b_id}-${r.a_id}-${i}`}>
                <td className="mono">{r.b_id}</td>
                <td className="mono">{r.a_id}</td>
                <td>{fmtInt(r.units)}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <div className="button-row">
        <button
          type="button"
          onClick={() => downloadJson(`SYNTHETIC-sandbox-events-${Date.now().toString(36)}.json`, { synthetic_badge: data.badge, ...exportLedger(core.ref, synEvents) })}
          data-testid="sandbox-export"
        >
          export sandbox decisions ({fmtInt(synEvents.length)} synthetic events, badge included)
        </button>
      </div>
      <p className="note">Sandbox decisions are namespaced synthetic:* and excluded from every real consequence count and receipt.</p>
    </>
  );

  function SyntheticActions({ target }: { target: ReviewTarget }) {
    return (
      <ReviewActions
        target={target}
        events={events}
        onRecord={(input) => record({ scenario_id: target.scenario_id, a_id: target.a_id, method_version: target.method_version, evidence_ref: target.evidence_ref, ...input })}
        onUndo={() => undo({ scenario_id: target.scenario_id, a_id: target.a_id, method_version: target.method_version, evidence_ref: target.evidence_ref })}
      />
    );
  }
}

export type { SynScoreKind };
